fragment GlobalSettingsParts on GlobalSettings {
  __typename
  site_name
  site_tagline
  site_description
  og_image
  default_meta_title
  default_meta_description
  social_x_url
  social_discord_url
  social_github_url
  contact_email
}

fragment SeoDefaultsParts on SeoDefaults {
  __typename
  title_suffix
  fallback_title
  fallback_description
  fallback_og_image
  robots_txt
}

fragment NavigationParts on Navigation {
  __typename
  items {
    __typename
    label
    href
    sort
    is_cta
  }
}

fragment FooterParts on Footer {
  __typename
  columns {
    __typename
    title
    sort
    links {
      __typename
      label
      href
      sort
    }
  }
}

fragment PageParts on Page {
  __typename
  title
  slug
  status
  meta_title
  meta_description
  sections {
    __typename
    ... on PageSectionsHero {
      heading
      subheading
      body
      badge_text
      cta_label
      cta_href
      cta_secondary_label
      cta_secondary_href
      background_image
    }
    ... on PageSectionsFeature_grid {
      heading
      subheading
      body
      badge_text
      cta_label
      cta_href
      cta_secondary_label
      cta_secondary_href
      background_image
    }
    ... on PageSectionsStats {
      heading
      subheading
      body
      badge_text
      cta_label
      cta_href
      cta_secondary_label
      cta_secondary_href
      background_image
    }
    ... on PageSectionsHow_it_works {
      heading
      subheading
      body
      badge_text
      cta_label
      cta_href
      cta_secondary_label
      cta_secondary_href
      background_image
    }
    ... on PageSectionsSecurity {
      heading
      subheading
      body
      badge_text
      cta_label
      cta_href
      cta_secondary_label
      cta_secondary_href
      background_image
    }
    ... on PageSectionsCards {
      heading
      subheading
      body
      badge_text
      cta_label
      cta_href
      cta_secondary_label
      cta_secondary_href
      background_image
    }
    ... on PageSectionsGlobal_finance {
      heading
      subheading
      body
      badge_text
      cta_label
      cta_href
      cta_secondary_label
      cta_secondary_href
      background_image
    }
    ... on PageSectionsFaq {
      heading
      subheading
      body
      badge_text
      cta_label
      cta_href
      cta_secondary_label
      cta_secondary_href
      background_image
    }
    ... on PageSectionsCta {
      heading
      subheading
      body
      badge_text
      cta_label
      cta_href
      cta_secondary_label
      cta_secondary_href
      background_image
    }
    ... on PageSectionsRich_text {
      heading
      subheading
      body
      badge_text
      cta_label
      cta_href
      cta_secondary_label
      cta_secondary_href
      background_image
    }
    ... on PageSectionsFinal_cta {
      heading
      subheading
      body
      badge_text
      cta_label
      cta_href
      cta_secondary_label
      cta_secondary_href
      background_image
    }
    ... on PageSectionsSwap_widget {
      heading
      subheading
      body
      badge_text
      cta_label
      cta_href
      cta_secondary_label
      cta_secondary_href
      background_image
    }
    ... on PageSectionsMarket_ribbon {
      heading
      subheading
      body
      badge_text
      cta_label
      cta_href
      cta_secondary_label
      cta_secondary_href
      background_image
    }
  }
}

fragment LegalPageParts on LegalPage {
  __typename
  title
  slug
  status
  meta_title
  meta_description
  updated_at
  body
}

fragment FaqItemParts on FaqItem {
  __typename
  question
  answer
  sort
  category
}

fragment WhatsappPreviewLinkParts on WhatsappPreviewLink {
  __typename
  key
  og_title
  og_description
  og_image
  url_path
  is_active
}
