export type {
  Page,
  PageSection,
  SectionType,
  GlobalSettings,
  NavItem,
  FooterColumn,
  FooterLink,
  FaqItem,
  LegalPage,
  SeoDefaults,
  WhatsAppPreviewLink,
} from './types';
export {
  getGlobalSettings,
  getBranding,
  getNavigation,
  getFooterColumns,
  getPageBySlug,
  getSeoDefaults,
  getFaqItems,
  getLegalPage,
  getLegalPages,
  getWhatsAppPreviewLink,
} from './queries';
